export * from './pinball'
export { PinballConfig } from './pinballConfig.interface'
export { status } from './status.enum'
export { pinballState } from './pinballState.interface'
export { pinballReducer } from './pinball.reducer'