export * from './pinball'
export { PinballConfig } from './pinballConfig.interface'
export { status } from './status.enum'
export { PinballState } from './PinballState.interface'
export { pinballReducer } from './pinball.reducer'